---
# inspo: https://github.com/LGUG2Z/nixos-wsl-starter/blob/master/.github/workflows/build.yml
name: "Release custom WSL tarball and NixOS ISO"
on:
  push:
    tags:
      - v*
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - name: Build tarball
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin run .#nixosConfigurations.workchng.config.system.build.tarballBuilder

      - name: Build ISO
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin build .#nixosConfigurations.iso1chng.config.system.build.isoImage

      - name: Rename ISO
        run: sudo mv result/iso/nixos-*.iso nixos.iso

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: nixos.wsl
          path: nixos.wsl

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: nixos.iso
          path: nixos.iso

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nixos.wsl
            nixos.iso
